name: build

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  build:
    strategy:
      matrix:
        value: [ { os: windows-latest, ninja-platform: win, output-name: windows, output-path: build/mousy.exe }, { os: ubuntu-latest, ninja-platform: linux, output-name: linux, output-path: build/mousy } ]
    name: build-${{ matrix.value.output-name }}
    runs-on: ${{ matrix.value.os }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: lts/*
      - run: npm ci

      - uses: wirekang/setup-ninja@v1
        with:
          platform: ${{ matrix.value.ninja-platform }}
          tag: v1.11.1

      - name: Generate VERSION
        run: npx semantic-release --dry-run --no-ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: workflow-scripts/build.sh

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.value.output-name }}
          path: ${{ matrix.value.output-path }}

  release-github:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v3
        with:
          path: release-assets
      - uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: lts/*
      - run: npm ci
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
